[package]
name = "api"
version = "0.4.0"
edition.workspace = true
publish = false
authors = ["slowlydev"]

[dependencies]
shared = { workspace = true }
archive = { path = "../archive" }
axum = { workspace = true, features = ["http2"] }
tower-http = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
ical = "0.11"
chrono = { workspace = true }
cached = { version = "0.56.0", features = ["disk_store", "async"] }
regex = "1.12.2"
rusqlite = { workspace = true }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
